# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19a1f3d09ea4b65d2cb38680f9093c6c3746c7d13662586f723add4b795b10fe3a48b9d7b8aaadca2d008fa1184235653cfba04696031a44eaef4f107f87e7aa

test:
  secret_key_base: c4ab5daa1cf09bf9b42fa724c35d76518398d5c68fe14c4d92a5cde57d191466f92979e4f1f87254a393205687fafa1164d35e6f13573d67308c8a58677804a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
